config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'cats#index'
  resources :cats do
    resources :comments, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy



  validates :name, presence: true
  validates :name, length: { minimum: 5 }
  validates :description, length: { maximum: 500 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :cat
  after_create :send_comment_email

  RATINGS = {
    'one star': '1_star',
    'two stars': '2_stars',
    'three stars': '3_stars',
    'four stars': '4_stars',
    'five stars': '5_stars'
  }

  def humanized_rating
    RATINGS.invert[self.rating]
  end

  def send_comment_email
      NotificationMailer.comment_added(self).deliver_now
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :cat
  mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :cat
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true, with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  def index
    @cat = Cat.all.page(params[:page]).per_page(10)
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = current_user.cat.create(cat_params)
    if @cat.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @cat = Cat.find(params[:id])
    @comment = Comment.new
    @photo =Photo.new
  end

  def edit
    @cat = Cat.find(params[:id])

    if @cat.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end
  end

  def destroy
    @cat = Cat.find(params[:id])
    if @cat.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end
    @cat.destroy
    redirect_to root_path
  end

  private

  def cat_params
    params.require(:cat).permit(:name, :description)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @cat = Cat.find(params[:cat_id])
    @cat.comments.create(comment_params.merge(user: current_user))
    redirect_to cat_path(@cat)
  end

  private

  def comment_params
    params.require(:comment).permit(:message, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/cats/edit.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Fix that Cat!</h1>
  <%= simple_form_for @cat do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :picture %>
  <br />
    <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/cats/index.html.erb
<% @cat.each do |cat| %>
  <div class="booyah-box col-10 offset-1">
    <h1><%= link_to cat.name, cat_path(cat) %></h1><br />
    <p><%= cat.description %></p><br />

    <%= will_paginate @cat %>
  

   <% if @cat.previous_page %>
    <%= link_to "< Previous", params.merge(page: @cat.previous_page) %>
    <% end %>
  Page <%= @cat.current_page %> of <%= @cat.total_pages %>
    <% if @cat.next_page %>
    <%= link_to "Next >", params.merge(page: @cat.next_page) %>
    <% end %>

    <% if cat.user.present? %>
      <small><%= cat.user.email %></small>
    <% end %>

    <% if place.comments.present? %>  
      <div class="col-12">
        <blockquote>
          <% if comment.humanized_rating.present? %>
            <b><%= cat.comment.last.humanized_rating %></b> -
          <% end %>
            <%= cat.comments.last.message %>
            <small><%= cat.comments.last.user.email %></small>
        </blockquote>
      </div>
    <% end %>

  </div>
  <hr />
  <% end %>

app/views/cats/new.html.erb
<div class="booyah-box col-10 offset-1">
<h1>Who's the Coolest Cat</h1>
  <%= simple_form_for @cat do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :picture %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/cats/show.html.erb
<h1>That's the Cat's Pajamas!</h1>

<div class="booyah-box col-10 offset-1">
  <h1><%= @cat.name %></h1><br />
  <br/><br/>
  <p><%= @cat.description %></p>
  



  <div class="float-right">
    <% if current_user && current_user == @cat.user %>
      <%= link_to 'Edit', edit_cat_path(@cat), class: 'btn btn-primary' %>
    <% end %>
      <%= link_to 'Destroy', cat_path(@cat), method: :delete, data: {confirm: 'You do not want this kitty anymore? :('}, class: 'btn btn-danger' %>
  </div>
</div>

<div class="clear"></div> 

  <div class="booyah-box col-10 offset-1">

    <h1>How Was Your Experience?</h1>
    <!-- Button trigger modal -->
      <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#mycommentModal">
              Review that cat!
    </button>
     
      <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myphotoModal">
              Add a Cat!
        </button>
      </div>
  </div>


 
<!-- Modal -->

<div class="modal fade" id="mycommentModal" tabindex="-1" role="dialog" aria-labelledby="mycommentModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="mycommentModalLabel">Add a comment</h4>
      <%= simple_form_for [@place, @comment] do |f| %>
        <div class="modal-body">
          <%= f.input :message %>
          <%= f.input :rating, as: :select, collection: Comment::RATINGS %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Add a Comment", class: 'btn btn-primary' %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

  <div class="booyah-box col-10 offset-1">
    <h1 class="float-left">Comments:</h1>

<div class="clear"></div>

  <div class="row">
   <% @place.comments.each do |comment| %>
    <div class="col-12 col-sm-6">
        <div>
          <blockquote>
          <% if comment.humanized_rating.present? %>
            <b><%= comment.humanized_rating %></b> -
          <%= comment.message %>
          <% end %>
          <small><%= comment.user.email %></small>
          </blockquote>          </div>
  
        </div>
        
    <% end %>

  </div>
      <div class="row">
        <% @place.photos.each do |photo| %>
          <div class="col-12 col-sm-6">
            <%= image_tag photo.picture.url, class: 'photo' %>
            <%= photo.caption %>
          </div>
       <% end %>
      </div>



<!-- Modal -->
<div class="modal fade" id="myphotoModal" tabindex="-1" role="dialog" aria-labelledby="myphotoModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myphotoModalLabel">Add a photo</h4>
  <%= simple_form_for @photo, url: place_photos_path(@place) do |f| %>
        <div class="modal-body">
          <%= f.input :picture %>
          <%= f.input :caption %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Add a Photo", class: 'btn btn-primary' %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Cat'sPJs</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to 'CatsPajamas', root_path, class: 'navbar-brand' %>


    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item">
            <%= link_to new_cat_path, class: 'nav-link' do %>
              <i class="fas fa-cat"></i>
              Add Cool Cat
            <% end %>
          </li>
        </ul>
         <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

      <% if notice.present? %>
        <p class="alert alert-info"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>


    <%= yield %>

  </body>
</html>